name: 'Upload to codecov.io'
description: 'Uploade python coverage prepared by aio-libs/prepare-coverage action to codecov.io'
inputs:
  artifact:
    description: 'The artifact name to load coverage chunks from'
    required: false
    default: 'coverage'
  fail_ci_if_error:
    description: 'Fail CI if error'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact }}
        path: ${{ runner.temp }}/coverage
    - name: Collect names
      id: meta
      run: |
        FILES=$(ls --dired | tr '\n' ' ')
        FILES2="${FILES% }"
        echo "::set-output name=files::${FILES2// /,}"
      working-directory: ${{ runner.temp }}/coverage
      shell: bash
    - name: Upload coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ${{ steps.meta.outputs.files }}
        directory: ${{ runner.temp }}/coverage
        fail_ci_if_error: ${{ inputs.fail_ci_if_error }}
