name: 'Upload Image'
description: 'Uploade Docker image as an artifact'
inputs:
  artifact:
    description: 'The artifact name to store coverage chunk'
    required: false
    default: 'coverage'
  fail_ci_if_error:
    description: 'Fail CI if error'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact }}
        path: ${{ runner.temp }}/coverage
    - name: Collect names
      id: meta
      run: |
        FILES=$(ls --dired | tr '\n' ' ')
        echo "::set-output name=files::${FILES# // /,}"
      working-directory:: ${{ runner.temp }}/coverage
      shell: bash
    - name: Upload coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ${{ steps.meta.outputs.files }}
        directory: ${{ runner.temp }}/coverage
        fail_ci_if_error: ${{ inputs.fail_ci_if_error }}
